# Generated by Django 5.1.1 on 2024-09-30 14:12

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('job_location', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('internship', 'Internship'), ('cdd', 'CDD'), ('cdi', 'CDI')], default='cdi', max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], default='fulltime', max_length=20, null=True)),
                ('work_preference', models.CharField(blank=True, choices=[('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='on_site', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unique_id', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('adresse', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobrecruitementAPI.platformuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='jobrecruitementAPI.platformuser')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobrecruitementAPI.platformuser')),
            ],
        ),
    ]
