# Generated by Django 5.1.1 on 2024-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
