# Generated by Django 5.1.1 on 2024-09-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0002_education_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
    ]
