# Generated by Django 5.1.1 on 2024-09-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0004_education_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='adresse',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', max_length=150),
        ),
    ]
