# Generated by Django 5.1.1 on 2024-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0005_remove_platformuser_adresse_platformuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=150),
        ),
    ]
