# Generated by Django 5.1.1 on 2024-09-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0006_remove_experience_description_experience_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
