# Generated by Django 5.1.1 on 2024-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0007_platformuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='github_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='linkedin_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='portfolio_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
