# Generated by Django 5.1.1 on 2024-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0008_platformuser_github_link_platformuser_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], default='fulltime', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='availability',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='proficiency',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='resume_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
