# Generated by Django 5.1.1 on 2024-10-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0009_experience_job_type_platformuser_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='birth_Date',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='sexe',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=30),
        ),
    ]
