# Generated by Django 5.1.1 on 2024-10-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0010_platformuser_birth_date_platformuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformuser',
            old_name='sexe',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='desiredjob',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desired_job', to='jobrecruitementAPI.platformuser'),
        ),
    ]
