# Generated by Django 5.1.1 on 2024-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0011_rename_sexe_platformuser_gender_desiredjob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='availability',
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='birth_Date',
            field=models.DateField(blank=True, default='1999-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='github_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='portfolio_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='proficiency',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='resume_file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=30, null=True),
        ),
    ]
