# Generated by Django 5.1.1 on 2024-10-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0013_education_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='location',
        ),
    ]
