# Generated by Django 5.1.1 on 2024-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0015_alter_platformuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
