# Generated by Django 5.1.1 on 2024-10-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0016_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='unique_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
