# Generated by Django 4.2.5 on 2024-10-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0017_alter_platformuser_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesiredJob',
        ),
    ]
