# Generated by Django 4.2.5 on 2024-11-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobrecruitementAPI', '0018_delete_desiredjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='birth_Date',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='education',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='course_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grading_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='passing_out_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='still_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='total_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='domain_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='primary_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='tools_technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='variable_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='adhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='current_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='disability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='ex_military',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='govt_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='military',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='permanent_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='reserve_forces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='state',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_summary', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jobrecruitementAPI.platformuser')),
            ],
        ),
        migrations.AddField(
            model_name='platformuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
